#!/usr/bin/env bash

# Directory where all coding projects will be cloned and stored.
code_directory="$HOME/code"
# Directory where a local copy of the Laptop repository will be cloned and stored.
laptop_repo_directory="$code_directory/laptop"

# Check if Laptop exists locally
if [ ! -d "$laptop_repo_directory" ]; then
    # Laptop doesn't exist locally, clone it.
    mkdir -p $laptop_repo_directory
    git clone git@github.com:ssmereka/laptop.git "$laptop_repo_directory"

    if [ ! -d "$laptop_repo_directory" ] || [ ! -f "$laptop_repo_directory/setup.sh" ]; then
        echo -e "\n🔴 Error:  Failed to clone Laptop to \"$laptop_repo_directory\".\n"
        exit 1
    fi
else
    cd $laptop_repo_directory

    # Pull the lastest changes from the Laptop Trunk branch.
    git fetch
    git reset --hard
    git checkout main
    git pull origin main
fi

# Run the macOS install script
chmod +x "$laptop_repo_directory/scripts/mac"
"$laptop_repo_directory/scripts/mac"
