#!/bin/zsh

# LAPTOP
# Make with ❤️ by Scott Smereka


# Global Configurations

# The following variables are user-configurable using the custom_config.sh script.
# These values are set and defined in the "set_global_configurations" method.
code_directory=""
laptop_local_directory=""
laptop_custom_directory=""
laptop_repo_directory=""
remote_laptop_base_url=""
remote_laptop_ssh_url=""

secret_item_name_git=""
secret_field_name_git_email=""
secret_field_name_git_name=""
secret_field_name_git_username=""
secret_item_name_ssh_key=""
secret_field_name_ssh_key_public=""


# The following variables are generated based on the global configurations in the 
# "set_global_configurations" method.
laptop_custom_config_script=""
laptop_custom_pre_install_script=""
laptop_custom_post_install_script=""
laptop_custom_pre_uninstall_script=""
laptop_custom_post_uninstall_script=""

# The following variables are used to store secrets obtained from 1Password and 
# injected into configurations during the script execution.
git_email=""
git_name=""
git_ssh_public_key=""
git_username=""


# Dynamic Global Variables

# Get the processor architecture from the operating system. Where "x86_64" 
# is an Intel processor and "arm64" is an Apple Silicon processor.
processor_architecture="$(uname -m)"

# Set variables based on the processor architecture.
# Exit the script if the processor architecture is not supported.
if [ "$processor_architecture" = "arm64" ]; then
    HOMEBREW_PREFIX="/opt/homebrew"
elif [ "$processor_architecture" = "x86_64" ]; then
    HOMEBREW_PREFIX="/usr/local"
else
    exit_with_error "Unsupported processor architecture: $processor_architecture"
fi


# Global Configurations

# Sets default values for the script's global variables. Then sources the user's
# custom configuration script that can override those values. Finally variables
# such as custom script paths are updated based on those new values.
set_global_configurations() {
    # Directory where all coding projects will be cloned and stored.
    code_directory="$HOME/code"

    # Directory where local Laptop configurations are stored. Laptop will create files
    # in this directory and link them to appropriate locations. Users can modify these
    # files as needed. Laptop will always require confirmation or a force flag before
    # overwriting files in this directory.
    laptop_local_directory="$HOME/.config/laptop"

    # Path to the user's optional custom configuration script. This file is executed before
    # commands are executed, allowing users to set or override variables and methods.
    laptop_custom_config_script="$HOME/.laptop/custom_config.sh"

    # Directory where a user's custom scripts are stored. Laptop will run and source 
    # files from this directory, make sure proper permissions are set. Laptop will always
    # require confirmation or a force flag before overwriting files in this directory.
    laptop_custom_directory="$HOME/.laptop"

    # Directory where a local copy of the Laptop repository will be cloned and stored.
    laptop_repo_directory="$code_directory/ssmereka/laptop"

    # Base URL for the remote Laptop repository.
    remote_laptop_base_url="https://raw.githubusercontent.com/ssmereka/laptop/refs/heads/main"

    # The URL used to clone the remote Laptop repository via SSH.
    remote_laptop_ssh_url="git@github.com:ssmereka/laptop.git"
    
    # The name of the 1Password "item" where the Git configurations exist, including email, name, and
    # username.
    secret_item_name_git="GitHub"

    # Name of the 1Password "field" in the item "secret_item_name_git" that contains the email address that
    # should be used by the Git client.
    secret_field_name_git_email="GitHub Email"

    # Name of the 1Password "field" in the item "secret_item_name_git" that contains the name that
    # should be used by the Git client.
    secret_field_name_git_name="Name"

    # Name of the 1Password "field" in the item "secret_item_name_git" that contains the git username that
    # should be used by the Git client.
    secret_field_name_git_username="GitHub Username"

    # The name of the 1Password "item" where the Git SSH Key configurations exist. This key should be
    # added to your remote Git repository, eg. GitHub.
    secret_item_name_ssh_key="GitHub SSH Key"

    # Name of the 1Password "field" in the item "secret_item_name_ssh_key" that contains the public ssh key
    # used by your remote Git repository, eg. GitHub.
    secret_field_name_ssh_key_public="public key"


    # Run the user's custom configuration script to override any variables.
    run_custom_script "$laptop_custom_config_script" "custom configuration script" false

    # Validate that all required variables are set to non-empty string values.
    require_non_empty_string_variable "code_directory"
    require_non_empty_string_variable "laptop_local_directory"
    require_non_empty_string_variable "laptop_custom_config_script"
    require_non_empty_string_variable "laptop_custom_directory"
    require_non_empty_string_variable "laptop_repo_directory"
    require_non_empty_string_variable "remote_laptop_base_url"
    require_non_empty_string_variable "remote_laptop_ssh_url"
    require_non_empty_string_variable "secret_item_name_git"
    require_non_empty_string_variable "secret_field_name_git_email"
    require_non_empty_string_variable "secret_field_name_git_name"
    require_non_empty_string_variable "secret_field_name_git_username"
    require_non_empty_string_variable "secret_item_name_ssh_key"
    require_non_empty_string_variable "secret_field_name_ssh_key_public"


    # The following paths can be derived from the global configuration variables.

    # Path to the user's optional custom pre install script. This file is executed before
    # the install command.
    laptop_custom_pre_install_script="$laptop_custom_directory/custom_pre_install.sh"

    # Path to the user's optional custom post install script. This file is executed after
    # the install command.
    laptop_custom_post_install_script="$laptop_custom_directory/custom_post_install.sh"

    # Path to the user's optional custom pre uninstall script. This file is executed before
    # the install command.
    laptop_custom_pre_uninstall_script="$laptop_custom_directory/custom_pre_uninstall.sh"

    # Path to the user's optional custom post uninstall script. This file is executed after
    # the install command.
    laptop_custom_post_uninstall_script="$laptop_custom_directory/custom_post_uninstall.sh"
}


# Methods

# Clears any variables that may be storing secrets pulled from 1Password.
clear_secrets() {
    log_header "🔒" "Clear Secrets from Memory"
    log "Erasing secret variables \"git_email\", \"git_name\", \"git_ssh_public_key\", and \"git_username\" from memory."

    unset git_email
    unset git_name
    unset git_ssh_public_key
    unset git_username
}

# Clone the remote Laptop repository locally using SSH, if it doesn't already exist.
clone_laptop_repository() {
    if [[ ! -d "$laptop_repo_directory" ]]; then
        mkdir -p $laptop_repo_directory
        git clone $remote_laptop_ssh_url "$laptop_repo_directory"

        if [[ ! -f "$laptop_repo_directory/src/mac" ]]; then
            error "Failed to clone Laptop from \"$remote_laptop_ssh_url\" to \"$laptop_repo_directory\"."
            log_command "git clone $remote_laptop_ssh_url \"$laptop_repo_directory\""
            exit 1
        fi
    fi
}

# Create a custom configuration file for Laptop that the user can modify.
configure_laptop_script() {
    
    log_header "🔧" "Setup Custom Laptop Configuration"
    
    # By default, use the remote Laptop repository source files when configuring the computer.
    local laptop_examples_location="$remote_laptop_base_url/examples"

    if is_laptop_installed; then
        # Use the local files for configuration
        laptop_examples_location="$laptop_repo_directory/examples"
    fi

    copy_file "$laptop_examples_location/custom_config.sh" "$laptop_custom_config_script"

    attention_prompt="Open the custom configuration file now? [Y/n]"
    attention_text="Customize Laptop by modifying the file \"$laptop_custom_config_script\"."

    if log_attention_with_prompt "$attention_prompt" "$attention_text"; then
        # Open the custom configuration file for editing.
        if [ -d "/Applications/Visual Studio Code.app" ]; then
            code "$laptop_custom_config_script"
        else
            open -e "$laptop_custom_config_script"
        fi
    fi
}


# Configure the 1Password GitHub CLI plugin so that it uses the Personal Access Token
# from 1Password for authentication.
configure_gh() {
    log_header "😸" "Configuring GitHub CLI"

    github_plugin_config_path="$HOME/.config/op/plugins/gh.json"

    if [[ ! -f "$github_plugin_config_path" ]]; then
        attention_text="Initializing the 1Password GitHub CLI Plugin. Follow these steps:"
        attention_text+="\n"
        attention_text+="\n\t1. Make sure you have a valid GitHub Personal Access Token stored in 1Password in a field named \"token\"."
        attention_text+="\n\t2. When asked to locate your token, navigate to the name of the 1Password item where your Personal Access Token was stored."
        attention_text+="\n\t3. When asked to configure when the chosen credentials will be used, select \"Use as global default on my system.\""
        attention_text+="\n"
        attention_text+="\n\tMore info can be found here:"
        attention_text+="\n\thttps://developer.1password.com/docs/cli/shell-plugins/github/#step-2-configure-your-default-credentials"

        if log_attention_with_prompt "" "$attention_text"; then
            log_attention "Requesting Unlock of 1Password to configure the GitHub plugin."
            op signin
            
            log "Initializing the 1Password GitHub CLI plugin."
            op plugin init gh
        else
            log "The 1Password GitHub CLI plugin configuration was cancelled by the user."
            return 1
        fi
    fi

    log "Verifying 1Password GitHub plugin"
    op plugin inspect gh

    attention_text="Check if the verification was successful.\n"
    attention_text+="\n\tIf you encounter an issue try deleting the configuration at \"$github_plugin_config_path\", then try again."

    if ! log_attention_with_prompt "" "$attention_text"; then
        exit_with_error "The 1Password GitHub CLI plugin configuration was cancelled by the user."
    fi
}

# Create a Git configuration file with the user's GitHub information from 1Password.
# Parameters:
#   laptop_src_location: A local directory path or a remote URL for the Laptop source code
#                        directory. Defaults to the "laptop_$laptop_repo_directory/src" variable.
configure_git() {
    laptop_src_location=${1:-"$laptop_repo_directory/src"}

    log_header "🔧" "Configuring Git"

    if [[ -z "$git_email" || -z "$git_name" || -z "$git_username" || -z "$git_ssh_public_key" ]]; then
        get_secrets
    fi

    # Create a local Git allowed signers file from the Laptop template.
    local_git_allowed_signers="$laptop_local_directory/.git-allowed-signers"
    copy_file "$laptop_src_location/.git-allowed-signers" "$local_git_allowed_signers"
    chmod 600 "$local_git_allowed_signers"

    # Create a local Git configuration file from the Laptop template.
    local_gitconfig="$laptop_local_directory/.gitconfig"
    copy_file "$laptop_src_location/.gitconfig" "$local_gitconfig"

    # Replace the allowed signers template variables using the information from 1Password.
    sed -i '' "s|GIT_NAME|${git_name}|" "$local_git_allowed_signers"
    sed -i '' "s|GIT_SSH_PUBLIC_KEY|${git_ssh_public_key}|" "$local_git_allowed_signers"

    # Replace the gitconfig template variables using the information from 1Password.
    sed -i '' "s|GIT_EMAIL|${git_email}|" "$local_gitconfig"
    sed -i '' "s|GIT_NAME|${git_name}|" "$local_gitconfig"
    sed -i '' "s|GIT_SSH_PUBLIC_KEY|${git_ssh_public_key}|" "$local_gitconfig"
    sed -i '' "s|GIT_USERNAME|${git_username}|" "$local_gitconfig"

    # Replace the gitconfig template allowed signers path variable with the location of the newly
    # configured allowed signers file.
    sed -i '' "s|PATH_TO_GIT_ALLOWED_SIGNERS|${local_git_allowed_signers}|" "$local_gitconfig"

    # Symbolically link the .gitconfig to the proper location.
    link_file "$local_gitconfig" "$HOME/.gitconfig"  
}

# Configure Mise to use the Laptop configuration files.
# Parameters:
#   laptop_src_location: A local directory path or a remote URL for the Laptop source code
#                        directory. Defaults to the "$laptop_repo_directory/src" variable.
configure_mise() {
    laptop_src_location=${1:-"$laptop_repo_directory/src"}

    log_header "🔧" "Configuring Mise"

    # Create a local Mise configuration file.
    copy_file "$laptop_src_location/.mise_config.toml" "$laptop_local_directory/.mise_config.toml"
    link_file "$laptop_local_directory/.mise_config.toml" "$HOME/.config/mise/config.toml"

    # Create a local Default Gems file.
    copy_file "$laptop_src_location/.default-gems" "$laptop_local_directory/.default-gems"
    link_file "$laptop_local_directory/.default-gems" "$HOME/.default-gems"

    # Trust the local configuration file to prevent prompts in the automated install.
    mise trust "$HOME/.config/mise/config.toml" || true
}

# Configure SSH to use the SSH keys in 1Password.
# Parameters:
#   laptop_src_location: A local directory path or a remote URL for the Laptop source code
#                        directory. Defaults to the "$laptop_repo_directory/src" variable.
configure_ssh() {
    laptop_src_location=${1:-"$laptop_repo_directory/src"}

    log_header "🔧" "Configuring SSH"

    # Create the default SSH directory (if it doesn't already exist)
    # and configure SSH to lookup SSH keys in 1Password
    mkdir -p "$HOME/.ssh/"
    chmod 700 "$HOME/.ssh"

    # Create a local .ssh_config configuration file from the Laptop template.
    local_ssh_config_path="$laptop_local_directory/.ssh_config"
    copy_file "$laptop_src_location/.ssh_config" "$local_ssh_config_path"
    
    # Grant the owner read/write permissions to the local SSH configuration file.
    # This is the required permission level for SSH to use the file.
    chmod 600 "$local_ssh_config_path"

    # Symbolicially link the local ssh config to the default location.
    link_file "$local_ssh_config_path" "$HOME/.ssh/config"
    
    # Create a local 1Password agent configuration file from the Laptop template.
    local_onepassword_agent_path="$laptop_local_directory/agent.toml"
    copy_file "$laptop_src_location/agent.toml" "$local_onepassword_agent_path"
    
    # Symbolicially link the local 1Password agent configuration to the default location.
    mkdir -p "$HOME/.config/1Password/ssh/"
    link_file "$local_onepassword_agent_path" "$HOME/.config/1Password/ssh/agent.toml"

    # Follow 1Password's recommendation to create a shortcut to the 1Password SSH Agent 
    # Integration, ie "~/.1password/agent.sock".
    mkdir -p "$HOME/.1password"
    link_file "$HOME/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock" "$HOME/.1password/agent.sock"
}

# Configure ZSH to use the Laptop configuration files.
# Parameters:
#   laptop_src_location: A local directory path or a remote URL for the Laptop source code
#                        directory. Defaults to the "$laptop_repo_directory/src" variable.
configure_zsh() {
    laptop_src_location=${1:-"$laptop_repo_directory/src"}

    log_header "🔧" "Configuring ZSH"

    # Create a local ZSH configuration file.
    copy_file "$laptop_src_location/.zshrc" "$laptop_local_directory/.zshrc"
    link_file "$laptop_local_directory/.zshrc" "$ZDOTDIR/.zshrc"

    # Create custom local ZSH configuration files.
    copy_file "$laptop_src_location/.zshrc_aliases" "$laptop_local_directory/.zshrc_aliases"
    copy_file "$laptop_src_location/.zshrc_methods" "$laptop_local_directory/.zshrc_methods"

    # Create a Atuin configuration file.
    copy_file "$laptop_src_location/atuin_config.toml" "$laptop_local_directory/atuin_config.toml"
    link_file "$laptop_local_directory/atuin_config.toml" "$HOME/.config/atuin/config.toml"
}

# Copy a file from the source path to the destination path if the file 
# does not already exist. When "overwrite" is true, the file will be replaced.
# Parameters:
#   source_path: The path to the source file to copy or URL of the file to download.
#   destination_path: The destination path where the file will be copied or downloaded.
#   overwrite: A boolean indicating whether to replace the destination file; defaults to false.
copy_file() {
    source_path=$1
    destination_path=$2
    overwrite=${3:-false}

    destination_directory="$(dirname "${destination_path}")"
    mkdir -p "$destination_directory"

    if [[ $overwrite == true || ! -f "$destination_path" ]]; then
        if [[ "$source_path" == http* ]]; then
            log "Downloading file from \"$source_path\" to \"$destination_path\""
            curl -o "$destination_path" "$source_path"
        else
            log "Copying file from \"$source_path\" to \"$destination_path\""
            cp "$source_path" "$destination_path"
        fi
    else
        log "No changes to file at \"$destination_path\"."
    fi
}

clear_laptop_configs() {
    log "Removing 1Password GitHub CLI configurations."
    op plugin clear gh

    log "Removing local Laptop configurations. Any changes made after the Laptop install will be" \
        "removed."
    rm -rf "$laptop_local_directory"
}

# Display an error message
error() {
    print -- " 🔴 [$(date '+%T')] ERROR: "$*"\n"
}

# Handle error messages by printing them and exiting with a failure status.
exit_with_error() {
    error "$*"
    exit 1
}

# Get secrets from 1Password and store them in global variables. This is a separate method to
# so secrets can be gathered at the start of the script to prevent user interactions in the 
# middle of a lengthy script.
get_secrets() {
    log_header "🔐" "Gathering Secrets"

    # Make sure 1Password has an account configured and app integration enabled.
    if [[ $(op account list --format=json 2>/dev/null) == "[]" ]]; then
        exit_with_error "There are no accounts configured for use with 1Password CLI. You must"\
                "enable app integration and then rerun this script.\n\n\t "\
                "Guide: https://developer.1password.com/docs/cli/app-integration/"
    fi

    log_attention "Requesting Unlock of 1Password to access the following information:" \
        "\n\n\t1. Item: \"$secret_item_name_git\"" \
        "\n\t   * Field: \"$secret_field_name_git_email\"" \
        "\n\t   * Field: \"$secret_field_name_git_username\"" \
        "\n\t   * Field: \"$secret_field_name_git_name\"" \
        "\n\n\t2. Item: \"$secret_item_name_ssh_key\"" \
        "\n\t   * Field: \"$secret_field_name_ssh_key_public\""

    $(op signin)

    log "Retrieving fields \"$secret_field_name_git_email\", \"$secret_field_name_git_name\", and" \
        "\"$secret_field_name_git_username\" from 1Password item \"$secret_item_name_git\"."

    git_email=$(op item get "$secret_item_name_git" --fields "$secret_field_name_git_email")
    git_name=$(op item get "$secret_item_name_git" --fields "$secret_field_name_git_name")
    git_username=$(op item get "$secret_item_name_git" --fields "$secret_field_name_git_username")

    if [[ -z "$git_email" || -z "$git_name" || -z "$git_username" ]]; then
        exit_with_error "Failed to lookup secret fields \"email\", \"name\", and \"username\"" \
                        "from item \"GitHub\" in 1Password. Make sure they exist."
    fi

    log "Retrieving field \"$secret_field_name_ssh_key_public\" from 1Password item \"$secret_item_name_ssh_key\"."
    
    git_ssh_public_key=$(op item get "$secret_item_name_ssh_key" --fields "$secret_field_name_ssh_key_public")

    if [[ -z "$git_ssh_public_key" ]]; then
        exit_with_error "Failed to lookup secret fields \"public keyl\" from item" \
                        "\"GitHub\" in 1Password. Make sure it exists."
    fi
}

# Install Xcode Command Line Tools, like git
install_apple_developer_tools() {
    if ! xcode-select -p &> /dev/null; then
        log_header "🍏" "Installing Apple's Developer Tools"
        xcode-select --install

        log_header "🍏" "Accepting the Apple Xcode License"
        sudo xcodebuild -license accept
    fi
}

# Install applications using Homebrew
install_apps() {
    log_header "🔧" "Installing Homebrew Applications"

    brew bundle --file=- <<EOF
    brew 'atuin' # https://atuin.sh
    brew 'awscli' # https://docs.aws.amazon.com/cli/
    brew 'curl' # https://curl.se
    brew 'coreutils' # https://formulae.brew.sh/formula/coreutils
    brew 'gawk' # https://www.gnu.org/software/gawk/
    brew 'gh' # https://cli.github.com
    brew 'gmp' # https://gmplib.org/
    brew 'gnupg' # https://www.gnupg.org
    brew 'libyaml' # https://pyyaml.org/wiki/LibYAML
    brew 'mise' # https://mise.jdx.dev
    brew 'openssl@3' # https://www.openssl.org/
    brew 'postgresql' # https://www.postgresql.org
    brew 'rustup-init' # https://rustup.rs
EOF

    # Initialize rustup with the default stable Rust toolchain non-interactively, if
    # it's not already installed and configured.
    if ! command -v rustup >/dev/null 2>&1; then
        rustup-init -y
    fi

    log_header "🔧" "Installing Applications"

    if ! brew list --cask visual-studio-code &>/dev/null; then
        log_header "🔧" "Installing Visual Studio Code"
        brew install --cask visual-studio-code
    else
        log "Visual Studio Code is already installed"
    fi

    if ! brew list --cask 1password-cli &>/dev/null; then
        log_header "🔧" "Installing 1Password CLI"
        brew install --cask 1password-cli
    else
        log "1Password CLI is already installed."
    fi

    install_mise_tools
    install_or_update_nvm
}



# Install and configure the user's PATH to include Homebrew. Or update 
# Homebrew if it's already installed.
install_or_update_homebrew() {
    if [[ $(command -v brew) == "" ]]; then
        log_header "🍺" "Installing Hombrew"
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

        # Add Homebrew to the user's PATH, if it's not already there.
        if [[ ":$PATH:" == *":$HOMEBREW_PREFIX/bin:"* ]]; then
            export PATH=$HOMEBREW_PREFIX/bin:$PATH
        fi
    else
        log_header "🍺" "Updating Homebrew"
        brew update --force # https://github.com/Homebrew/brew/issues/1151
    fi
}

# Installs NVM using the official install script from the NVM repository.
# If NVM is already installed, it will update NVM to the latest version.
# Verifies that NVM is installed and working by checking the version.
install_or_update_nvm() {
    log_header "🔧" "Installing or updating Node Version Manager (NVM)"

    # The PROFILE=/dev/null will prevent the setup script from updating
    # the bash profile(s), as this is already configured by the Laptop script.
    PROFILE=/dev/null bash -c 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash'

    # Load nvm for the current shell, if it is not already loaded.
    local nvm_dir="${NVM_DIR:-${XDG_CONFIG_HOME:-$HOME/.nvm}}"
    export NVM_DIR="$nvm_dir"
    if [ -s "$NVM_DIR/nvm.sh" ]; then
        . "$NVM_DIR/nvm.sh"
    fi

    # Verify that nvm is installed and working.
    if command -v nvm >/dev/null 2>&1; then
        echo "\n✅ Node Version Manager (NVM) version $(nvm --version) is installed."
    else
        echo "\n❌ Node Version Manager (NVM) installation failed.\n" >&2
    fi
}

# Configures the mise global tools using the defined configuration file, then installs those tools.
install_mise_tools() {
    # Create the default global Mise configuration file, if it doesn't already exist
    configure_mise

    log_header "🔧" "Installing Mise Tools"

    # Add Cargo to the PATH, if it's not already there.
    if ! echo "$PATH" | grep -q "$HOME/.cargo/bin"; then
        export PATH="$HOME/.cargo/bin:$PATH"
    fi

    # Install all tools defined in Mise default global configuration
    (cd "$HOME" && mise install --yes)
}

# Returns zero when the Laptop script is considered installed locally, otherwise returns one.
is_laptop_installed() {
    if [ -d "$laptop_repo_directory" ]; then
        return 0 # Labtop is already installed.
    else
        return 1 # Laptop is not yet installed.
    fi
}

# Create a soft symbolic link from the source file to the destination file, overwriting the link
# if it already exists.
# Parameters:
#   source_path: The path to the source file to copy or URL of the file to download.
#   destination_path: The destination path where the file will be copied or downloaded.
link_file() {
    source_path="$1"
    destination_path="$2"

    # The "ln" command will fail if the directories in the destination 
    # path do not exist. Create all the destination directories, if they do not exist.
    mkdir -p "$(dirname "$destination_path")"

    log "Creating a new symbolic link from \"$source_path\" to \"$destination_path\""
    ln -sf "$source_path" "$destination_path"
}

# Display a message to the user.
log() {
    print -- "    [$(date '+%T')] $*\n"
}

# Display all global configuration settings.
log_config() {
    log_header "⚙️ " "Global Configuration Settings"
    
    log "Directories:"
    log "  code_directory:           \"$code_directory\""
    log "  laptop_local_directory:   \"$laptop_local_directory\""
    log "  laptop_custom_directory:  \"$laptop_custom_directory\""
    log "  laptop_repo_directory:    \"$laptop_repo_directory\""
    
    log "\nRemote Repository:"
    log "  remote_laptop_base_url:   \"$remote_laptop_base_url\""
    log "  remote_laptop_ssh_url:    \"$remote_laptop_ssh_url\""
    
    log "\n1Password Secret References:"
    log "  secret_item_name_git:                \"$secret_item_name_git\""
    log "  secret_field_name_git_email:         \"$secret_field_name_git_email\""
    log "  secret_field_name_git_name:          \"$secret_field_name_git_name\""
    log "  secret_field_name_git_username:      \"$secret_field_name_git_username\""
    log "  secret_item_name_ssh_key:            \"$secret_item_name_ssh_key\""
    log "  secret_field_name_ssh_key_public:    \"$secret_field_name_ssh_key_public\""
    
    log "\nCustom Script Paths:"
    log "  laptop_custom_config_script:         \"$laptop_custom_config_script\""
    log "  laptop_custom_pre_install_script:    \"$laptop_custom_pre_install_script\""
    log "  laptop_custom_post_install_script:   \"$laptop_custom_post_install_script\""
    log "  laptop_custom_pre_uninstall_script:  \"$laptop_custom_pre_uninstall_script\""
    log "  laptop_custom_post_uninstall_script: \"$laptop_custom_post_uninstall_script\"\n"
}

log_attention() {
    print -- " 🟠 [$(date '+%T')] ATTENTION: "$*"\n"
}

log_attention_with_prompt() {
    local prompt="${1:-Ready to continue? [Y/n]}"
    local text="${@:2}"

    log_attention "$text"
    read "response? 🤨 $prompt "
    print -- ""

    if [[ -z $response || $response =~ ^[Yy] ]]; then
        # User confirmed with an empty response (ie. pressed enter) or the letter "Y".
        return 0
    else
        # User declined by entering any value (length > zero) that is not "Y".
        return 1
    fi
}

log_command() {
    print -- "\n\t 🖥️   TERMINAL COMMAND: "$*""
    print -- "\t    ~~~~~~~~~~~~~~~~~\n"
}

# Display a distinct header message to the user.
# Parameters:
#   emoji: The emoji to display before the header text
#   text: The header text to display (will be uppercased)
log_header() {
    local emoji="$1 "
    local text="${(U)2}"
    local dashes="${(l:${#text}::~:)}"
    print -- "\n $emoji $text"
    print -- "     $dashes\n"
}

log_secrets() {
    log_header "🔐" "Current Secrets in Memory"

    log "  git_email:          \"$git_email\""
    log "  git_name:           \"$git_name\""
    log "  git_ssh_public_key: \"$git_ssh_public_key\""
    log "  git_username:       \"$git_username\"\n"
}

# Validate that a named variable exists and has a non-empty string value.
require_non_empty_string_variable() {
    local var_name="$1"
    local var_value="${(P)var_name}"

    if [[ -z "${var_value//[[:space:]]/}" ]]; then
        exit_with_error "The variable \"$var_name\" must be set to a valid value for Laptop to continue."
    fi
}

# Run a custom script located at the given path, if it exists. Verifies the script is 
# executable and asks for confirmation before running it, unless confirmation is disabled.
# Parameters:
#   custom_script_path:  The path to the custom script to run.
#   custom_script_name:  A friendly name for the script, used in log messages. Defaults to
#                        "custom script" if not provided.
#   require_confirmation: A boolean indicating whether to prompt the user for confirmation
#                         before running the script. Defaults to true.
run_custom_script() {
    custom_script_path="$1"
    custom_script_name="${2:-custom script}"
    require_confirmation=${3:-true}

    if [ -f "$custom_script_path" ]; then
        
        
        # Verify custom script is executable.
        if [ ! -x "$custom_script_path" ]; then
            log_header "💡" "Found $custom_script_name at path \"$custom_script_path\" with invalid permissions."
            exit_with_error "Custom script at path \"$custom_script_path\" is not executable. " \
                            "Please update the script's permissions.\n\n" \
                            "\tTry: chmod +x $custom_script_path"
        fi

        # Confirm user wants to run the custom script, unless confirmation is disabled
        if [[ $require_confirmation == true ]]; then
            log_header "💡" "Found $custom_script_name at path \"$custom_script_path\"."
            log "🤔 Would you like to run it?\n\n" \
                "> Press any key to run this file...\n"
            read -n 1
        fi

        log_header "🏃" "$custom_script_name"
        log "Running the $custom_script_name at path \"$custom_script_path\""


        # Execute the script in the current shell environment.
        set -a
        source "$custom_script_path"
        set +a
    fi 
}

# Update the local Laptop repository, pulling down all new changes. If there are local changes the
# user will be prompted to stash those changes before pulling. If the user declines the update will
# be cancelled, but the script will continue.
update_laptop_repository() {
    pushd $laptop_repo_directory > /dev/null

    log_header "🔁" "Updating Laptop Repository"

    # If there are changes in the local repository, ask the user if 
    # they want to stash and pull the latest changes.
    if [[ `git status --porcelain` || $(git rev-parse --abbrev-ref HEAD) != "main" ]]; then

        # Prompt to inform the user that there are unsaved changes in the Laptop git repository.
        local attention_prompt="Continue without pulling the latest changes? [Y/n]"
        local attention_text="Cannot pull the latest changes from the remote Laptop repository, "
        attention_text+="\n\tbecause there are local changes or you are not on the "main" branch."
        attention_text+="\n\n"
        attention_text+="\tY:  Proceed without the latest changes from the remote Laptop repository."
        attention_text+="\n\n"
        attention_text+="\t    OR"
        attention_text+="\n\n"
        attention_text+="\tN:  Stash the local changes, then pull the latest from the remote Laptop"
        attention_text+="\n\t    repository. Reapply the local changes with \"git stash pop\" command."

        if log_attention_with_prompt "$attention_prompt" "$attention_text"; then
            # User chose to continue without pulling the latest changes.
            log "Skipped pulling the latest changes from the remote Laptop repository."
            return
        else
            # User chose to stash the local changes and pull latest.
            log_attention "Stashing local changes. After Laptop completes you can restore those changes with:"
            log_command "cd '$laptop_repo_directory' && git stash pop"
            git stash
        fi
    fi

    log "\nChecking out the \"main\" branch and pulling changes.\n"
    git fetch
    git checkout main
    git pull origin main

    popd > /dev/null
}


# Command Methods

install() {
    force_flag="$1"

    log_header "💻" "Configuring your Laptop"

    # Run the user's custom pre-install script.
    run_custom_script "$laptop_custom_pre_install_script" "pre-install script"

    # By default, use the remote Laptop repository source files when configuring the computer.
    local laptop_src_location="$remote_laptop_base_url/src"
    
    if is_laptop_installed; then
        # Prompt the user for access to 1Password before long running tasks.
        get_secrets

        # Use the local files for configuration
        laptop_src_location="$laptop_repo_directory/src"

        # Update the script's source code before continuing
        update_laptop_repository
    fi

    if [[ $force_flag == true ]]; then
        # Delete all local configurations so that they will be recreated with the default values.
        # Effectively removing any local changes made after the script was initially run.
        clear_laptop_configs
    fi

    install_apple_developer_tools
    install_or_update_homebrew
    install_apps
    configure_ssh "$laptop_src_location"
    configure_git "$laptop_src_location"
    configure_zsh "$laptop_src_location"

    configure_gh

    clone_laptop_repository

    # Run the user's custom post-install script.
    run_custom_script "$laptop_custom_post_install_script" "post-install script"

    clear_secrets

    log_header "🎉" "Installation is complete"
    log_attention "Close this terminal session and start a new one to use the updated configurations.\n"
}

# Remove everything this script added during installation.
uninstall() {
    # TODO: This method is incomplete at the moment.

    # Run the user's custom pre-uninstall script.
    run_custom_script "$laptop_custom_pre_uninstall_script" "pre-uninstall script"

    log_header "🔨" "Uninstalling Applications"

    if brew list atuin &>/dev/null; then
        brew uninstall atuin # https://atuin.sh
    fi

    uninstall_nvm

    if brew list mise &>/dev/null; then
        brew uninstall mise # https://mise.jdx.dev
    fi

    # TODO: Ask if you want to uninstall these
    # brew uninstall gh
    # brew uninstall coreutils
    # brew uninstall curl
    # brew uninstall gawk
    # brew uninstall gnupg # https://www.gnupg.org
    # rustup-init

    log_header "🗂️" "Removing Application Data"

    # Remove Laptop data
    rm -rf "$laptop_local_directory"

    # Remove Atuin Application Data
    rm -rf "$HOME/.config/atuin"

    # Run the user's custom post-uninstall script.
    run_custom_script "$laptop_custom_post_uninstall_script" "post-uninstall script"

    log "\n🎉 Done. Restart your shell to complete the uninstall."
}

# Removes NVM if it is installed.
uninstall_nvm() {
    local nvm_dir="${NVM_DIR:-${XDG_CONFIG_HOME:-$HOME/.nvm}}"
    if [ -d "$nvm_dir" ]; then
        echo "\n💥 Uninstalling Node Version Manager (NVM).\n"
        command -v nvm >/dev/null && nvm unload
        rm -rf "$nvm_dir"
    fi
}

# Interpret commandline arguments and run the appropriate methods.
main() {
    configure_flag=false
    install_flag=false
    uninstall_flag=false
    force_flag=false

    additional_args=()

    # Parse commandline arguments
    while [[ $# -gt 0 ]]; do
        case "$1" in
            -f|--force)
                force_flag=true
                ;;
            configure)
                configure_flag=true
                ;;
            install)
                install_flag=true
                ;;
            uninstall)
                uninstall_flag=true
                ;;
            *)
                additional_args+=("$1")
                ;;
        esac
        shift
    done

    # Configure global variables
    set_global_configurations

    # Run the appropriate command(s)

    if [[ $configure_flag == true ]]; then
        configure_laptop_script

    elif [[ $uninstall_flag == true ]]; then
        uninstall
    
    elif [[ $install_flag == true ]]; then
        install $force_flag
    
    # By default, run the install command.
    else
        install $force_flag
    fi
}

# Hey... Thank you for reading this script before running some strangers code.


# Run main only if the script is executed directly; not when sourced.
if [[ "${(%):-%N}" == "$0" ]]; then
    main "$@"
fi
